#!/bin/bash

# Nagios Exit Codes
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

# set default values for the thresholds
WARN=80
CRIT=90

usage()
{
cat <<EOF

Check Linux Memory Usage

     Options:
	-H         Hostname/IP Address
        -w         Warning threshold as percentage (def: 80)
        -c         Critical threshold as percentage (def: 90)

Sample Usage: $0 -H 10.1.1.1 -w 80 -c 90
EOF
}


while getopts "H:w:c:h" ARG;
do
        case $ARG in
                H) MYHOST=$OPTARG
                   ;;
                w) WARN=$OPTARG
                   ;;
                c) CRIT=$OPTARG
                   ;;
                h) usage
                   exit
                   ;;
        esac
done

# Check Memory Usage

MYDIRFORTMP=/var/nagiosramdisk/tmp
if [ -w "$MYDIRFORTMP" ]; then
  MYOUTMP="$MYDIRFORTMP/$MYHOST-memcheckout"
  MYOUTMPERR="$MYDIRFORTMP/$MYHOST-memcheckouterr"
else
  MYOUTMP="/tmp/$MYHOST-memcheckout"
  MYOUTMPERR="/tmp/$MYHOST-memcheckouterr"
fi
#memusage=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_me -a '../../../../usr/bin/top -b -n1' | grep "Cpu(s)" | awk '{print $2 + $4}' | awk '{print substr($1, 1, length($1)-2)}'`
#memusage=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_me -a '../../../../usr/bin/top -b -n1' | grep "Cpu(s)" | awk '{print $2 + $4}' |  awk '{printf "%0.0f\n", $1}'`
#memusageout=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_me -a '../../../../usr/bin/top -b -n1'`

#memusageout=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_mem -a 80,50,40 90,60,50 1 3`

###-----
memusageout=`/bin/timeout 60s /usr/local/nagios/libexec/check_by_ssh -H $MYHOST -o StrictHostKeyChecking=no -C '/usr/local/nagios/libexec/mycheck_linux_mem -w 80 -c 90' -t 240 -l nagios -E`
###-----

echo $memusageout 2> $MYOUTMPERR > $MYOUTMP

#memusage=`cat "$MYOUTMP" | grep "Cpu(s)" | awk '{print $2 + $4}' |  awk '{printf "%0.0f\n", $1}'`
#memusage=`cat "$MYOUTMP" | awk '{print $8}' | cut -d= -f2 | tr -d '%' | tr -d ',' | awk '{print 100 - $1}'`
#memusage=`cat "$MYOUTMP" | awk '{print $27 + $29}' |  awk '{printf "%0.0f\n", $1}'`

###-----
memusage=`cat "$MYOUTMP"`
###-----

# End Checking

RESULT=$(echo "Memory Usage = $memusage% | 'mem usage'=$memusage%;$WARN;$CRIT;")

MYOKNOT=$( cat "$MYOUTMP" | grep "Memory Usage" )
MYOKNOTERR=$( cat "$MYOUTMPERR" )
MYRESULTERR=$( cat "$MYOUTMPERR" )
if [ ! -z "$MYOKNOTERR" ]; then
	RESULT="$MYRESULTERR"
        echo "UNKNOWN: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
        exit $UNKNOWN;
fi
MYRESULT=$( cat "$MYOUTMP" )
if [ -z "$MYOKNOT" ]; then
	RESULT="$MYRESULT"
        echo "UNKNOWN: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
        exit $UNKNOWN;
else
	echo $MYRESULT
fi
#if [ "$memusage" -gt $CRIT ]; then
#	echo "CRITICAL: $RESULT"
#        rm -f $MYOUTMP $MYOUTMPERR
#	exit $CRITICAL;
#elif [ "$memusage" -gt $WARN ]; then
#	echo "WARNING: $RESULT"
#        rm -f $MYOUTMP $MYOUTMPERR
#	exit $WARNING;
#else
#	echo "OK: $RESULT"
#        rm -f $MYOUTMP $MYOUTMPERR
#	exit $OK;
#fi

