#!/bin/bash

# Nagios Exit Codes
OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3

# set default values for the thresholds
WARN=80
CRIT=90

usage()
{
cat <<EOF

Check Linux SWAP Usage

     Options:
	-H         Hostname/IP Address
        -w         Warning threshold as percentage (def: 80)
        -c         Critical threshold as percentage (def: 90)

Sample Usage: $0 -H 10.1.1.1 -w 80 -c 90
EOF
}


while getopts "H:w:c:h" ARG;
do
        case $ARG in
                H) MYHOST=$OPTARG
                   ;;
                w) WARN=$OPTARG
                   ;;
                c) CRIT=$OPTARG
                   ;;
                h) usage
                   exit
                   ;;
        esac
done

# Check SWAP Usage

MYDIRFORTMP=/var/nagiosramdisk/tmp
if [ -w "$MYDIRFORTMP" ]; then
  MYOUTMP="$MYDIRFORTMP/$MYHOST-swapcheckout"
  MYOUTMPERR="$MYDIRFORTMP/$MYHOST-swapcheckouterr"
else
  MYOUTMP="/tmp/$MYHOST-swapcheckout"
  MYOUTMPERR="/tmp/$MYHOST-swapcheckouterr"
fi
#swapusage=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_me -a '../../../../usr/bin/top -b -n1' | grep "Cpu(s)" | awk '{print $2 + $4}' | awk '{print substr($1, 1, length($1)-2)}'`
#swapusage=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_me -a '../../../../usr/bin/top -b -n1' | grep "Cpu(s)" | awk '{print $2 + $4}' |  awk '{printf "%0.0f\n", $1}'`

swapusageout=`/usr/local/nagios/libexec/check_nrpe -H $MYHOST -t 90 -c check_me -a '../../../../usr/bin/top -b -n1'`

#swapusage=`cat "$MYOUTMP" | grep "Cpu(s)" | awk '{print $2 + $4}' |  awk '{printf "%0.0f\n", $1}'`
swapusage=`cat "$MYOUTMP" | grep "Swap" | awk '{print $60/$56 * 100.0}' |  awk '{printf "%0.0f\n", $1}'`

# End Checking

RESULT=$(echo "SWAP Usage = $swapusage% | 'swap usage'=$swapusage%;$WARN;$CRIT;")

MYOKNOT=$( cat "$MYOUTMP" | egrep '^top' )
MYOKNOTERR=$( cat "$MYOUTMPERR" )
MYRESULTERR=$( cat "$MYOUTMPERR" )
if [ ! -z "$MYOKNOTERR" ]; then
	RESULT="$MYRESULTERR"
        echo "UNKNOWN: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
        exit $UNKNOWN;
fi
MYRESULT=$( cat "$MYOUTMP" )
if [ -z "$MYOKNOT" ]; then
	RESULT="$MYRESULT"
        echo "UNKNOWN: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
        exit $UNKNOWN;
fi
if [ "$swapusage" -gt $CRIT ]; then
	echo "CRITICAL: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
	exit $CRITICAL;
elif [ "$swapusage" -gt $WARN ]; then
	echo "WARNING: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
	exit $WARNING;
else
	echo "OK: $RESULT"
        rm -f $MYOUTMP $MYOUTMPERR
	exit $OK;
fi

